In [1]:
#Initialization packages
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from math import pi
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, execute
from qiskit.tools.visualization import circuit_drawer
from qiskit.quantum_info import state_fidelity
from qiskit import BasicAer
backend = BasicAer.get_backend('unitary_simulator')


/usr/local/lib/python3.5/dist-packages/marshmallow/schema.py:364: ChangedInMarshmallow3Warning: strict=False is not recommended. In marshmallow 3.0, schemas will always be strict. See https://marshmallow.readthedocs.io/en/latest/upgrading.html#schemas-are-always-strict
  ChangedInMarshmallow3Warning


In [2]:
q = QuantumRegister(1)

**U3 Gate**

In [3]:
qc = QuantumCircuit(q)
qc.u3(pi/2,pi/2,pi/2,q)
qc.draw()

In [4]:
job = execute(qc, backend) 
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j   ,  0.   -0.707j],
       [ 0.   +0.707j, -0.707+0.j   ]])

**I gate**

In [5]:
qc = QuantumCircuit(q)
qc.iden(q)
qc.draw()

In [6]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)


array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

**Pauli X Gate**

In [7]:
c = QuantumCircuit(q)
qc.x(q)
qc.draw()

In [8]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[0.+0.j, 1.+0.j],
       [1.+0.j, 0.+0.j]])